List<int> practiceIndexes = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
];

List<String> practiceTitles = [
  'Hello World',
  'Calculating the average of numbers in a given list',
  'Swapping numbers without a temporary variable',
  'Reversing a given integer',
  'Printing odd numbers within a given range',
  'Finding the sum of digits in a number',
  'Printing all numbers in a given range divisible by a given number',
  'Finding smallest divisor of an integer',
  'Counting the number of Digits in a number',
  'Checking if a number is a palindrome',
  'Reading a number \'n\' and printing the series \'1+2t...tn=\'',
  'Reading a number \'n\' and printing the Natural numbers',
  'Printing an identity',
  'Printing an inverted',
  'Computing simple interest given all the required values',
  'Checking whether a given year is a Leap year',
  'Reading height in centimeters and then converting to inch and feet',
  'Taking the temperature in Celcius and converting',
  'Computing prime',
  'Generating all the divisors of an integer',
  'Printing largest even and largest odd number in a list',
  'Printing table of a given number',
  'Checking if a number is an Armstrong number',
  'Printing the Pascal\'s triangle for n number of rows',
  'Checking if a number is a perfect number',
  'Checking if a number is a strong number',
  'Finding LCM',
  'Finding GCD',
  'Finding area of a triangle',
  'Finding gravitational force acting between two object',
];
